apiVersion: v1
kind: Pod

metadata:
  name: nginx-lab
  labels:
    app: nginx-lab

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html/index.html

  volumes:
  - name: html-volume
    hostPath:
      path: /data/index.html
      type: File
